### ISSUE TITLE
Join page - mobile adjustment

### ISSUE THREAD

**Issue by bitkarrot** [plebnet-dev/website#12]
The join page does not seem to adjust to mobile narrower width on Android.

**Comment by bitkarrot** [comment]
Example of what I see on Android Mobile for Join page, white boxes should go inline

![photo_2023-06-24 19 03 31](https://github.com/plebnet-dev/website/assets/73979971/2a19a813-d6b2-494b-84d1-863b12d930ef)

**Comment by eriknewland** [comment]
Added some flexbox/responsiveness 

![Screen Shot 2023-07-09 at 8 09 45 AM](https://github.com/plebnet-dev/website/assets/114263701/d93f64a8-16fd-41a3-b7c0-61d6be33529b)

**Comment by eriknewland** [comment]
Deployment link:

https://plebdevs-eriknewland.vercel.app/

**Comment by bitkarrot** [comment]
Thanks for the PR, a few things. I don't know how difficult it would be to make this adjustment, so let me know if its doable or not

1. when viewing full browser size, it doesn't go back to side by side and the rectangles are of different sizes. 
2. Its not quite obvious when I click on the 'Individual' or 'corporate' boxes that there is a form, sometimes, it my window is smaller. How can we address this better? either by 

A) redirecting to a separate page with the form 
B) pushing the form to the top and the links to the bottom
C) doing a modal where the form pops up over

**Comment by bitkarrot** [comment]
Example of what i see in Firefox desktop browser

<img width="723" alt="Screenshot 2023-07-09 at 1 01 45 PM" src="https://github.com/plebnet-dev/website/assets/73979971/95f168ec-e9ee-47c1-89d0-38f1871938b1">

**Comment by eriknewland** [comment]
Interesting, I'll try and track down what's going on with the flex issue there. And as for number 2, I think a Modal would probably be best. I'll get back to you later today with some updates

**Comment by plebnetdev** [comment]
this is good, close?
