### ISSUE TITLE
[ISSUE] Thank You page and Tip Jar returns 404

### ISSUE THREAD

**Issue by TekkadanPlays** [plebnet-dev/website#128]
<img width="717" alt="Screenshot_2024-04-30_at_6 06 51_PM" src="https://github.com/plebnet-dev/website/assets/93434084/c2325190-f6a9-45d2-b3b7-9da0e603c409">

**Comment by bitkarrot** [comment]
closed with 99096cee8f5b626c1cb725f6084442d1435d1401
