### ISSUE TITLE
[ISSUE] Projects Page 404's

### ISSUE THREAD

**Issue by TekkadanPlays** [plebnet-dev/website#129]
https://plebnet.dev/projects

<img width="662" alt="Screenshot_2024-04-30_at_6 47 14_PM" src="https://github.com/plebnet-dev/website/assets/93434084/1f1c6cc3-bda9-44f4-8496-398bc8b8f544">

**Comment by plebnetdev** [comment]
For now, just make  /projects redirect to /resources, we can put back the fancy stuff later. @amsalmeron

**Comment by bitkarrot** [comment]
closed with 99096cee8f5b626c1cb725f6084442d1435d1401
