### ISSUE TITLE
Individual and corporate membership sign up - suggested info changes

### ISSUE THREAD

**Issue by Bitc0indad** [plebnet-dev/website#13]
Creating an issue against the information fields like “sponsor” result shows “True” just a minor adjustment to “yes” or “interested “ etc.

**Comment by eriknewland** [comment]
Done
![Screen Shot 2023-07-09 at 7 53 47 PM](https://github.com/plebnet-dev/website/assets/114263701/71d08f56-5642-4f08-bbbf-4c899d233e79)
