### ISSUE TITLE
Email Content to individual and corporate membership work at sign up - Broken Links

### ISSUE THREAD

**Issue by Bitc0indad** [plebnet-dev/website#14]
"Recent articles" links are not rerouting to webpage or repos within email body. 

Gmail and Protonmail same issues.

**Comment by eriknewland** [comment]
![Screen Shot 2023-07-09 at 5 26 02 PM](https://github.com/plebnet-dev/website/assets/114263701/edc85ebf-4a6b-4ede-8259-62d7c6b8ec8e)
![Screen Shot 2023-07-09 at 5 26 08 PM](https://github.com/plebnet-dev/website/assets/114263701/9541ac43-3d49-4e25-9f18-8e45b15bcba1)

Fixed
