### ISSUE TITLE
Add FAQ discord to bottom Nav

### ISSUE THREAD

**Issue by plebnetdev** [plebnet-dev/website#18]
Suggested Location. 

<img width="1000" alt="Screenshot 2023-07-10 at 9 47 56 PM" src="https://github.com/plebnet-dev/website/assets/139167260/18dac439-508a-4447-8234-438b4b6f6720">

**Comment by bitkarrot** [comment]
Add the FAQ Link : https://discord.gg/UFJp72cf to the bottom nav

**Comment by bitkarrot** [comment]
GOOD FIRST ISSUE!!

**Comment by Bitc0indad** [comment]
Discord link pasted into HTML is expired after 7 days appears invalid on webpage. 

Use this link instead never expires: https://discord.gg/PdBcqnAyCD

**Comment by bitkarrot** [comment]
@Bitc0indad as a moderator you can generate a new link that doesn't expire. Please make a new PR to help fix this. Thanks

**Comment by bitkarrot** [comment]
assigning to @Bitc0indad
