### ISSUE TITLE
artifact on the creation of invoices

### ISSUE THREAD

**Issue by plebnetdev** [plebnet-dev/website#24]
@eriknewland  the invoice will probably works but i just noticed this weird artifact of satoshi price, probably created via the API vs manually in the interface. the manual creation just says satoshis, so maybe there is an extra conversion in the code somewhere?

lnurlp through API
<img width="594" alt="Screenshot 2023-07-13 at 11 49 21 PM" src="https://github.com/plebnet-dev/website/assets/139167260/5ca76d8f-7b46-484b-9090-4b2484b7c2d2">

lnurlp on Manual creation
<img width="468" alt="Screenshot 2023-07-13 at 11 52 26 PM" src="https://github.com/plebnet-dev/website/assets/139167260/db2669ab-4433-41cf-b1b8-5222eff29718">

**Comment by eriknewland** [comment]
Should be fixed now, also moved the fees into env variables to make it easier to adjust in the future. 

![Screen Shot 2023-07-21 at 3 34 42 PM](https://github.com/plebnet-dev/website/assets/114263701/6f9b441a-9be0-4803-b277-6d96256dc08d)

**Comment by bitkarrot** [comment]
er did this get merged without review? @eriknewland 

the fee is 100,000 not 10k. 

and also 300,000 not 30k
