### ISSUE TITLE
Consolidate links in Webform

### ISSUE THREAD

**Issue by bitkarrot** [plebnet-dev/website#26]
- Does Form Fail gracefully if LNBits is down?
- Consolidate link e.g. https://sats.lnaddy.com/ into ENV variable.

```const response = await fetch(`https://sats.lnaddy.com/lnurlp/api/v1/links/${paylinkID}```

https://github.com/plebnet-dev/website/blob/main/src/components/SignUpFormIndiv.svelte
https://github.com/plebnet-dev/website/blob/main/src/components/SignUpFormCorp.svelte

**Comment by eriknewland** [comment]
did someone mess with the links for the components? Everything seems to be broken

**Comment by bitkarrot** [comment]
Nope. haven't touched anything on the main. Only you and I can merge and I will be hands off unless you ask for it, so that you can get experience driving merge to main and push to production

**Comment by bitkarrot** [comment]
@eriknewland  still open? if not, pls close, thanks
