### ISSUE TITLE
Add resource links to plebnet services

### ISSUE THREAD

**Issue by eriknewland** [plebnet-dev/website#37]
add a dropdown link called "resources" and add the LNBits  Testnet to it (testnet.plebnet.dev/)  

Will probably add a faucet later

**Comment by bitkarrot** [comment]
Potentially good links to add to resources: 

- LNBits Testnet
- Testnet Faucet
- Testnet Lightning Node (https://mempool.space/testnet/lightning/node/03ba00a57cec1cef4873065ad54d0912696274cc53155b29a3b1256720e33a0943) 
- Nostr Relay
- Signet Faucet

- Nostr NIP-5 and Lightning services (Nostr Kit) 

Design Wise, should this all be listed on a separate page or should we make them all dropdown links? 
The link list could potentially get really long 

Do Try and see what looks best and works best visually

**Comment by bitkarrot** [comment]
Reminder, we are using the astrowind template, see the demo for examples of dropdown links: 
https://astrowind.vercel.app/

😀

**Comment by bitkarrot** [comment]
@Bitc0indad Also consider mobile vs desktop, this is really a UI/UX thing to consider as the astrowind template does not have dropdowns on the mobile example and 95% of the world now is on mobile, https://astrowind.vercel.app/landing/mobile-app. In the footer you can have as many links and sections as you want and it should be fine. 

 I have made some edits to the comments above so pls have a look on github for latests

**Comment by bitkarrot** [comment]
- Add rebranded https://nostrogen.com/, see forked repo at: 
- https://github.com/plebnet-dev/nostrogen
