### ISSUE TITLE
Refactor and/or Full Rewrite for Registration page logic

### ISSUE THREAD

**Issue by bitkarrot** [plebnet-dev/website#47]
The following sections need to be refactored: 

Issues: 
- reduce and remove repeated code
- eliminate API keys that are checked in (bad practice)
- LNURLp should be an invoice generated in the satspay style where there is an automated time out, not this recurring generation of LNURLp which continously spam the database adding unnecessary and redundant entries.
- if we eliminate LNURLp usage more wallets can pay and we don't need to worry about compatibility
- Removing the continuous web page polling to check if payment has been made - this adds extra load to the server which is unnecessary and does not improve user experience at the cost of adding repeated 10 seconds calls to the LNBits server - just bad design, period. 
- Reduce the declaration of individual variables for the web form, instead use a json or other data structure. 
- Factor out repeated code in both corporate and individual pages such that methods that are repeated are pulled from a utility file and not repeated over both of the pages, thereby causing extra maintenance and errors in the future.

This is just a start, we'll deal with other things in the refactor as they come along. 

Code source to reference: 

 - https://github.com/plebnet-dev/website/blob/main/src/pages/Corp.astro
 - https://github.com/plebnet-dev/website/blob/main/src/pages/Indiv.astro
 - https://github.com/plebnet-dev/website/tree/main/src/pages/api

**Comment by bitkarrot** [comment]
- A Key part of this task is to replace the QR code section in the svelte in the form, remove it from the bottom of the current form and don't show the QR until the following page but use Satspayserver extension to show the QR payment code. This is BOLT11 and not a lnurlp, which means QR code will expire after about 15-20 minutes. 

- Using Satspay extension also avoids prevents the database from getting over loaded with lnurlp entries created every time someone clicks on the page (which is happening now)

- You can use the testnet server at https://testnet.plebnet.dev and htlc.me for lightning sats for testing

<img width="320" alt="Screenshot 2023-10-06 at 2 06 16 PM" src="https://github.com/plebnet-dev/website/assets/73979971/cb9d0d22-80c6-40de-90ad-a4ef9c5a0959">

**Comment by bitkarrot** [comment]
If the above is still confusing, I will cover the topics the lnurlp and satspay extensions on the Oct 16, workshop.

**Comment by bitkarrot** [comment]
Correction: Oct 15 Workshop

**Comment by bitkarrot** [comment]
@amsalmeron how is this coming along?

**Comment by amsalmeron** [comment]
@bitkarrot Having trouble connecting to an email delivery service

**Comment by bitkarrot** [comment]
How about if I set you up with an email forwarder and you try to make an account at sendgrid?

Will DM you
