### ISSUE TITLE
Add Author + Profile option to blog posts

### ISSUE THREAD

**Issue by bitkarrot** [plebnet-dev/website#5]
- Add Author to blog posts. Right now this doesn't exist (see image). 
- Add Autho to blog lists
- Add option for author name to link to a profile page on the website, where the author can update any information he/she wants to share.

 
<img width="577" alt="Screenshot 2023-06-22 at 11 10 15 AM" src="https://github.com/plebnet-dev/website/assets/73979971/cef691dc-b442-4f38-8976-c0cac81ba2c7">

**Comment by bitkarrot** [comment]
@Bitc0indad This was the issue we discussed about authors.

**Comment by bitkarrot** [comment]
GOOD FIRST ISSUE!!

**Comment by Bitc0indad** [comment]
> @Bitc0indad This was the issue we discussed about authors.

Thanks BK! I will review with Erik and get PR submitted for this.

**Comment by Bitc0indad** [comment]
> * Add Author to blog posts. Right now this doesn't exist (see image).
> * Add Autho to blog lists
> * Add option for author name to link to a profile page on the website, where the author can update any information he/she wants to share.
> 
> <img alt="Screenshot 2023-06-22 at 11 10 15 AM" width="577" src="https://user-images.githubusercontent.com/73979971/248019197-cef691dc-b442-4f38-8976-c0cac81ba2c7.png">

@bitkarrot this issue "Add option for author name to link to a profile page on the website, where the author can update any information he/she wants to share." Would this be a new header and footer etc Projects --- Blog --- Store --- Team --- About --- ?

**Comment by bitkarrot** [comment]
Not too sure what your comment means, do you mean profile pages? Yes there should be a separate folder and section in astro for this if people want to do it. That ground work should be laid out first before links are created. 

Also, Can you do a visual mockup of what you're trying to do?  It would help a lot to convey how you see it. thanks

**Comment by bitkarrot** [comment]
Still open? 

reassigning reviewr to @eriknewland
