### ISSUE TITLE
make shop link a permalink

### ISSUE THREAD

**Issue by bitkarrot** [plebnet-dev/website#57]
Turn this link (https://plebnet-dev.printify.me) into a permalink on all pages. so that the link is updated in only one place. 

For example of how permalinks should be updated see this PR: https://github.com/plebnet-dev/website/pull/46/files

<img width="495" alt="Screenshot 2023-10-07 at 9 31 41 PM" src="https://github.com/plebnet-dev/website/assets/73979971/26ff806d-e940-4c3b-8dc5-b97dd4aebb04">

**Comment by saucy-tech** [comment]
I'd like to be assigned this and give it a try.

**Comment by bitkarrot** [comment]
Assigned. Go for it!
