### ISSUE TITLE
Standardize metadata for blog posts

### ISSUE THREAD

**Issue by saucy-tech** [plebnet-dev/website#60]
Update Readme with helpful information for beginners to create blog posts. Will ensure consistency among posts, limit overuse of tags, and guide new users.

- Identify purpose of categories/tags (seo, site navigation, etc.)
- Standardize a list of categories/tags
- Standardize blog header
- Add helpful info to Readme for choosing categories/tags

![Screenshot 2023-10-07 at 10 27 23 PM](https://github.com/plebnet-dev/website/assets/125085502/b878d2b6-6b26-4576-9784-df249336171c)
<img width="506" alt="Screenshot 2023-10-08 at 1 10 58 PM" src="https://github.com/plebnet-dev/website/assets/125085502/5f55b471-a748-4e40-920b-b4f44cf21dfc">

**Comment by bitkarrot** [comment]
@saucy-tech Go for it! That's a great idea. We are already getting too many tags there. Thank you for initiative!

**Comment by bitkarrot** [comment]
@saucy-tech please pull from main. a lot of blog posts have been modified and updated. thanks.

**Comment by saucy-tech** [comment]
Created a PR. Let me know what you think about those categories. For tags, we may just need to review them for redundancy. I think next steps after approving would be to go back and update some of the blog posts.
