### ISSUE TITLE
Add your NIP-5 and lnurlp to .well-known

### ISSUE THREAD

**Issue by bitkarrot** [plebnet-dev/website#67]
- open for anybody to add. 
https://github.com/plebnet-dev/website/tree/main/public/.well-known

**Comment by BrutusBondBTC** [comment]
I can do this. I just need the plebnet,dev  npub.  Have you made one yet?

**Comment by bitkarrot** [comment]
Yup. You can Make one for yourself. its just adding an entry to the nostr.json

we don't have a social account for the org yet, mostly we still need a social media manager

**Comment by BrutusBondBTC** [comment]
awesome.

**Comment by bitkarrot** [comment]
@BrutusBondBTC  you still interested in this? i got something interesting in the pipeline
