### ISSUE TITLE
Should commit package-lock file

### ISSUE THREAD

**Issue by bliotti** [plebnet-dev/website#70]
Noticed [package-lock.json is ignored](https://github.com/plebnet-dev/website/blob/d2626a90a65154b0e6d55506f141ec193f4768f0/.gitignore#L22), IMO this file should be committed. 

Should help with the random build issues. 

> [The purpose of package-lock.json ](https://www.atatus.com/blog/package-json-vs-package-lock-json/#package-lock-json)is to ensure that the same dependencies are installed consistently across different environments, such as development and production environments. It also helps to prevent issues with installing different package versions, which can lead to conflicts and errors.

@bitkarrot @saucy-tech

**Comment by bitkarrot** [comment]
Right on! Anyone want to make a PR for this?

**Comment by saucy-tech** [comment]
Yes I'd like to do this, submitted PR #71

**Comment by bitkarrot** [comment]
Great. Waiting for @bliotti on the upgrade PR https://github.com/plebnet-dev/website/pull/72

he suggested that one be merged in first before your update, which means once the other one is in merged, you'll need to pull from main and redo, sorry about that.

the other #72  is worth taking a look at to see what he did for the astro3 upgrade

**Comment by saucy-tech** [comment]
I closed my previous PR to reconcile all the updates. Did a git reset, used node 18.6.1 with nvm, and reinstalled astro and dependencies. Looks like astro 3.4.1 just released this morning as well. I can still do a gitignore PR if needed.

**Comment by bitkarrot** [comment]
Actually reading the initial message, its the opposite - https://github.com/plebnet-dev/website/issues/70#issue-1957232379

@bliotti  is saying that the package-lock.json should be committed, not the reverse. I agree with him on this. 

What To Do: Run and build your updated branch on vercel, check that everything builds correctly,  then open a PR and commit the package-lock.json file. 

If you can open back the PR, appreciate it!

**Comment by bitkarrot** [comment]
closing as merged per #71
