### ISSUE TITLE
automate event.md update from Discord events.

### ISSUE THREAD

**Issue by bitkarrot** [plebnet-dev/website#73]
automate events from the Discord over to the markdown event.md post instead of updating it manually.

**Comment by bitkarrot** [comment]
P.S. @saucy-tech If you need a hint or tips on this, do let me know.

**Comment by Bitc0indad** [comment]
@asherp I believe we need to create a system that can parse and format event details from Discord and then update the markdown file accordingly.

**Comment by bitkarrot** [comment]
@Bitc0indad you can also look at this (https://github.com/plebnet-dev/website/pull/83/files) for reference. However I would rather the markdown blog page be updated and not a regular .astro page, as the markdown blog will always show up in the "Latest Blog Posts" Carousel at the bottom of main website page, see screenshot below. 

<img width="780" alt="Screenshot 2024-01-28 at 5 58 25 PM" src="https://github.com/plebnet-dev/website/assets/73979971/73b91c3d-ae4c-435e-ad38-2ddc2f7ae12f">
