### ISSUE TITLE
Review PR #72 current hash

### ISSUE THREAD

**Issue by bliotti** [plebnet-dev/website#75]
Review latest commit on PR #72, which is [24aca60](https://github.com/plebnet-dev/website/pull/72/commits/24aca60ac562c8f897539b925e54caf106fa3f48) atm.

Verify
- Able to spin up locally without issue. i.e.  `npm run dev` (note. `node` version requirement  is now >18 [see here](https://github.com/plebnet-dev/website/blob/24aca60ac562c8f897539b925e54caf106fa3f48/package.json#L43)) 
- visually compare this version has no noticeable changes in UI or performance.

**Comment by bitkarrot** [comment]
@bliotti still open? or can close?
