### ISSUE TITLE
Add Official Twitter Account

### ISSUE THREAD

**Issue by bitkarrot** [plebnet-dev/website#8]
- TBD

**Comment by Bitc0indad** [comment]
Do we have a plebnet.dev email to use for twitter and other social media signups? I think we can get away without mobile # for signups and could share password to email with administrators?

**Comment by bitkarrot** [comment]
closing this issue and merging it with nostr.  Everyone submitted only nostr npubs no twitter, and this makes sense. No rush needed into social media just yet, we're not ready.
