### ISSUE TITLE
404 page doesn't show 

### ISSUE THREAD

**Issue by bitkarrot** [plebnet-dev/website#82]
- 404 error page doesn't display when visiting a non-existent page on astro, unclear why?
-

**Comment by zachbitcoin** [comment]
- Just poking around. There is a duplicate closing head tag on line 24: https://github.com/plebnet-dev/website/blob/main/src/layouts/BaseLayout.astro
- Are we hosting with Netifly? Does it need a redirect file for the 404 page to load? https://docs.netlify.com/routing/redirects/redirect-options/#custom-404-page-handling
-- Maybe we just need to change the code in the netifly.toml file?

**Comment by bitkarrot** [comment]
@zachbitcoin we deployed on Vercel.
