### ISSUE TITLE
Store link on plebnet.dev gated behind unsafe warning

### ISSUE THREAD

**Issue by zachbitcoin** [plebnet-dev/website#89]
OS: Mac Big Sur
Chrome Version 118.0.5993.117 (Official Build) (arm64)
No browser extensions.

When clicking the Store button I am prompted with: <img width="1018" alt="Screen Shot 2023-11-21 at 6 37 17 AM" src="https://github.com/plebnet-dev/website/assets/85877659/bb23c376-998c-431b-9bc3-27cd4f4d1e6e">

**Comment by bitkarrot** [comment]
which store button, on which page?

**Comment by zachbitcoin** [comment]
> which store button, on which page?

<img width="1098" alt="Screen Shot 2023-11-26 at 7 55 23 PM" src="https://github.com/plebnet-dev/website/assets/85877659/9a7bcb7e-3566-4123-9b2a-fafc00191ec0">

https://plebnet-dev.printify.me/

**Comment by bitkarrot** [comment]
Note: possibly add target="_blank" but also rel="noopener noreferrer" , to see if these additions could fix this.

**Comment by asherp** [comment]
@bitkarrot we updated the site with your suggested modifications, but the error hasn't gone away. any other ideas?

**Comment by bitkarrot** [comment]
@asherp what does the error look like and on what browsers? is it only on Chrome? 

I presume this error only happens on click from the astro website, if you open a new browser with the link and referral does it also happen? I am out of ideas, maybe the Astro discord might have answers? https://discord.gg/astrodotbuild

**Comment by bitkarrot** [comment]
How about instead of open link we make it redirect?

**Comment by bliotti** [comment]
> @bitkarrot we updated the site with your suggested modifications, but the error hasn't gone away. any other ideas?

I can't reproduce anything either

**Comment by Bitc0indad** [comment]
<img width="2560" alt="Screenshot 2024-01-28 at 8 58 53 AM" src="https://github.com/plebnet-dev/website/assets/105452033/c18e4b1b-cf1b-497c-a41f-92102498b202">

On Google Chrome in Incognito mode I'm able to replicate the original issue see image attached.

**Comment by Bitc0indad** [comment]
<img width="2557" alt="Screenshot 2024-01-28 at 9 00 42 AM" src="https://github.com/plebnet-dev/website/assets/105452033/97478fec-a6c0-4573-9956-9ff42cba0e87">

Verification in inspector mode showing the suggested updates. 

<a href="https://plebnet-dev.printify.me" class="transition duration-150 ease-in-out dark:hover:text-white flex font-medium hover:text-gray-900 items-center px-4 py-3" rel="noopener noreferrer" target="_blank">Store</a>

**Comment by Bitc0indad** [comment]
Firefox Browser - unsafe warning is not prompted
<img width="1440" alt="Screenshot 2024-01-28 at 9 31 44 AM" src="https://github.com/plebnet-dev/website/assets/105452033/06ec1e69-081b-4e62-92e4-348024e53610">

**Comment by bliotti** [comment]
hmm, I tried chrome on mac incognito mode, clicking on store link from plebnet.dev site, but no warning popped up, I also tried this with enhanced security settings turned on too.

Safe Browsing site status checked out fine.
https://transparencyreport.google.com/safe-browsing/search?hl=en

Here's more info about the issue.  
https://support.google.com/chrome/answer/99020?hl=en&co=GENIE.Platform%3DDesktop#:~:text=Did%20you%20mean%20%5Bsite%20name,than%20the%20one%20you%20expected.

maybe google needs to index the store's site url.

maybe a redirect would solve this? idk

**Comment by Bitc0indad** [comment]
Understood we'll look into the redirect instead

**Comment by bliotti** [comment]
if this is only a minor annoyance, maybe put on back burner. it may solve itself overtime. 

if it's easy enough to grab another subdomain "plebnet-dev.printify.me" for printify and just point it to same place, that would fix it too.

**Comment by bitkarrot** [comment]
Can't grab another printify domain without the hassle of extra pay per month, extra hassle of maintenance. This is a low cost print on demand plan that does not have the flexibility of a custom domain name. 

We already don't have enough hands on board to maintain the current website as you can see there are still a lot of outstanding issues. 

it would be best to find a solution on astro instead.

**Comment by bitkarrot** [comment]
FWIW - oddly i don't see this problem with the link to mempool.space on the resources tab. So clearly this is something we are doing wrong with Astro on Chrome. Maybe compare the link setup between the two and that is where the issue is. 

@Bitc0indad @asherp

**Comment by bliotti** [comment]
mempool link goes to the official mempool.space domain, that's fine. 

The issue is only Chrome's. Chrome is trying to protect the user since "plebnet-dev" looks like the domain "plebnet.dev".

**Comment by bliotti** [comment]
Again I don't how much this is affecting users, I still can't reproduce it. (may want to test this on more browsers and on on mobile ones too) 

albeit another solution - not that clean, but use a different site you own that has a page for handling the redirect. 
Then store link would point to an obviously different named domain but then that page would redirect it to printly. 
"redirects as a service" lol

**Comment by bitkarrot** [comment]
Even simpler, a Domain level 301 redirect should do it. No page or server needed.
