### ISSUE TITLE
https://rates.plebnet.dev/ ERROR

### ISSUE THREAD

**Issue by Bitc0indad** [plebnet-dev/website#92]
<img width="865" alt="Screenshot 2024-01-03 at 7 52 23 PM" src="https://github.com/plebnet-dev/website/assets/105452033/0e60374f-b599-49fa-af9b-bbbf1cb71031">

This Serverless Function has crashed.

Your connection is working correctly.

Vercel is working correctly.

500: INTERNAL_SERVER_ERROR
Code: FUNCTION_INVOCATION_FAILED
ID: iad1::nvhts-1704340782249-f441b649492f

**Comment by Bitc0indad** [comment]
https://vercel.com/docs/error/application/FUNCTION_INVOCATION_FAILED

**Comment by bitkarrot** [comment]
@Bitc0indad assigning to you to fix. :)

**Comment by bitkarrot** [comment]
Please file issue over on https://github.com/plebnet-dev/rates
